import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'
import Link from '@/components/Link/Link'
import React from 'react'

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
})
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode
  modal: React.ReactNode
}>) {
  return (
    <html lang="en" className="h-full">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-full`}
      >
        <div className="bg-slate-300 p-4 w-full h-full">
          <div className="border-b-2 border-gray-600 mb-2">
            <Link href="/">home</Link>
          </div>

          <div>
            {children}
            {modal}
          </div>
        </div>
      </body>
    </html>
  )
}
