import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import Link from '@/components/Link'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-[100%] flex justify-center bg-neutral-50 `}
      >
        <div className="flex flex-col items-center h-screen w-full max-w-[1024px]">
          <header className="flex items-center justify-center py-2 w-full border-b-2 border-neutral-300">
            <Link href="/">Home</Link>
          </header>

          <main className="flex justify-center w-full h-full p-2">
            {children}
          </main>
        </div>
      </body>
    </html>
  )
}
