import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import Link from '@/components/Link'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-[100%]`}
      >
        <div className="grid grid-rows-[min-content_1fr] bg-neutral-50 h-screen gap-5 justify-center">
          <header className="flex items-center justify-center my-2">
            <Link href="/">Home</Link>
          </header>

          <main className="flex justify-center max-w-[1024px]">{children}</main>
        </div>
      </body>
    </html>
  )
}
