import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import Link from '@/components/Link'
import ReactQueryProvider from '@/components/ReactQueryProvider'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className="h-full">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-screen flex flex-col justify-start items-center bg-neutral-50`}
      >
        <ReactQueryProvider>
          <header className="flex items-center justify-center py-2 w-full border-b-2 border-neutral-300 h-fit">
            <Link href="/">Home</Link>
          </header>

          <main className="w-full p-4 overflow-auto flex justify-center">
            <div className="w-full max-w-[1024px] h-fit">
              {children}
            </div>
          </main>
        </ReactQueryProvider>
      </body>
    </html>
  )
}

