import type { Metadata } from 'next'
import { ReactNode } from 'react'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  first,
  second,
}: Readonly<{
  children: React.ReactNode
  first: ReactNode
  second: ReactNode
}>) {
  return (
    <div className="w-full h-full">
      {children}
      {first}
      {second}
    </div>
  )
}
